
image: docker
stages:
  - test
  - build-and-push
  - deploy

test:
  stage: test
  image: node
  before_script:
    - yarn install
  script:
    - yarn test --coverage

build-and-push:
  stage: build-and-push
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - export DOCKER_TAG=`echo ${CI_BUILD_REF_NAME} | sed s/master/latest/`
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json    
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/dockerfile --destination tevaum/countries:$DOCKER_TAG
  when: on_success

deploy-ssh:
  stage: deploy
  image: debian:stable-slim
  before_script:
    - export DOCKER_TAG=`echo ${CI_BUILD_REF_NAME} | sed s/master/latest/`
    - apt -qq update
    - apt install -qqy openssh-client
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - ssh -o "StrictHostKeyChecking no" -l tevaum 161.97.92.93 "docker pull tevaum/countries:$DOCKER_TAG && docker-compose -p countries -f /srv/countries/docker-compose.yml up -d"